# Generated by Django 4.2.4 on 2023-08-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ManyToManyField(to='home.person'),
        ),
    ]
